apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-service-monitor
  labels:
    release: adaptive-monitoring
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: adaptive-cache
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
      scrapeTimeout: 4s
